### ISSUE TITLE
Same patient is returned multiple times when queried on subject attributes

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-service#69] opened 2021-04-29 21:45 UTC
Have revised the original notebook on 09CO022 after the select p.* change.
See https://github.com/ianfore/cdatest/blob/main/09CO022%20Example%20on%20release%200.1.12.ipynb

There are still eight results returned by a query on subject attributes when there should be four. This is because the query is done on unnest(research subject) and there are two research subjects within each patient that match. 

Not sure if the query can be formulated in the boolean form in a way that gives the correct result, but identified a direct SQL query that ensures each patient is returned only once.

**Comment by YeastCell** [comment] 2021-09-01 21:42
@dionboles-asym @fkaufman-asym This is what I was talking about last week – hitting multiple matches for certain conditions that involve nested fields ultimately returns the same patient multiple times.

Here is an example with simplified data:

```
with baskets as
(
    select "A" as basket,
    [
        struct('apple' as item, 'fruits' as type),
        struct('pear' as item, 'fruits' as type),
        struct('chocolate' as item, 'sweets' as type)
    ] as groceries
    union all select "B" as basket,
    [
        struct('peach' as item, 'fruits' as type),
        struct('carrot' as item, 'vegetables' as type),
        struct('cookie' as item, 'sweets' as type)
    ] as groceries 
    union all select "C" as basket,
    [
        struct('watermelon' as item, 'fruits' as type),
        struct('potato' as item, 'vegetables' as type),
        struct('pumpkin' as item, 'vegetables' as type)
    ] as groceries 
)

select baskets.*
from baskets,
unnest(groceries) as _groceries
where _groceries.type = "fruits"
```

This is how I deal with it:

```
select baskets.basket, any_value(baskets.groceries) as groceries
from baskets,
unnest(groceries) as _groceries
where _groceries.type = "fruits"
group by baskets.basket
```

**Comment by YeastCell** [comment] 2021-10-14 18:33
Here is a simple query that shows the problem:

```
q1 = Q('ResearchSubject.associated_project = "CPTAC-2"')
q2 = Q('id = "05CO039"')

q = q1.And(q2)
r = q.run()
print(r)
```

Output:

```
QueryID: c378e4d4-335b-4fb5-be86-4b4d6f54c377
Query: SELECT all_v1.* FROM gdc-bq-sample.integration.all_v1 AS all_v1, UNNEST(ResearchSubject) AS _ResearchSubject WHERE ((_ResearchSubject.associated_project = 'CPTAC-2') AND (all_v1.id = '05CO039'))
Offset: 0
Count: 2
Total Row Count: 2
More pages: False
```

As Ian mentioned – this is caused by unnesting and finding two hits in the joint product after unnesting. There are two research subjects (both GDC and PDC) that have the field `associated_project` that equals to `CPTAC-2`. And it is obvious that we should get at most 1 patient row in the results since we hardcoded the patient ID to `05CO039`.

**Comment by YeastCell** [comment] 2021-10-14 18:41
Actually, here is the example when file format is included in the query:

```
q1 = Q('File.file_format = "mzML"')
q2 = Q('id = "05CO039"')

q = q1.And(q2)
r = q.run()
print(r)
```

Output:

```
QueryID: bcc38656-0c64-4db4-b2ce-64f6231f6219
Query: SELECT all_v1.* FROM gdc-bq-sample.integration.all_v1 AS all_v1, UNNEST(File) AS _File WHERE ((_File.file_format = 'mzML') AND (all_v1.id = '05CO039'))
Offset: 0
Count: 42
Total Row Count: 42
More pages: False
```

**Comment by YeastCell** [comment] 2021-10-14 18:44
@dionboles-asym @fkaufman-asym Can you please link this in the cda-python issues? I believe that this should be addressed in R2.0.
attn @DavidPotCanuck

**Comment by ACharbonneau** [comment] 2022-06-22 14:48
This has been fixed in release 3 (coming out end of June)

**Closed by ACharbonneau** 2022-06-22 14:48 UTC
Labels: bug
